---
- name: Copy the nginx configuration file
  become: true
  template: src=nginx.conf dest={{nginx_conf_dir}}/nginx.conf
  notify:
   - restart nginx
  tags: [configuration,nginx]

- name: Create the configurations for sites
  become: true
  template: src=piet-us dest={{nginx_conf_dir}}/sites-enabled/piet-us
  notify:
   - reload nginx
  tags: [configuration,nginx]

- name: Generate dhparams
  become: true
  shell: openssl dhparam -out /etc/nginx/dhparams.pem 2048
  args:
    creates: /etc/nginx/dhparams.pem

- name: Install nginx site for specified site
  become: true
  template:
    src: templates/nginx-le.conf
    dest: /etc/nginx/sites-enabled/le

- name: Reload nginx to activate specified site
  become: true
  service: name=nginx state=restarted
