---
- name: Remove existing notes folder
  become: true
  file: path=/home/notes/notes state=absent

- name: Create notes folder
  become: true
  file: path=/home/notes/notes state=directory owner=piet group=piet

- name: Copy notes from git repo
  git: repo="{{ repository }}/notes.git" dest="/home/{{ notes_user }}/notes" accept_hostkey=yes

- name: Modify owner of notes folder to notes user
  become: true
  file: path=/home/notes/notes state=directory owner=notes group=notes


