---
notes_user: "notes"
notes_group: "{{notes_user}}"
notes_service_name: "notes"
notes_log_dir: "/var/log/notes"
notes_pid_file: "/var/run/{{notes_service_name}}/agent.pid"
notes_install_dir: "/home/{{ notes_user }}"
notes_run_script: "{{ notes_install_dir }}/config/run.sh"
