---
- name: Remove existing html folder
  become: true
  file: path=/var/www/html state=absent

- name: Create html folder
  become: true
  file: path=/var/www/html state=directory owner=civil group=civil

- name: Copy piet.us from git repo
  git: repo={{ repository }}/piet.us.git dest=/var/www/html/ accept_hostkey=yes depth=1

- name: Installing jq
  become: yes
  apt:
    pkg: jq
    state: latest
